// Analysis core - pure TypeScript with no `vscode` imports. VS Code extension and
// evaluation procedure use structured outputs generated by same analysis core.
// Home of the domain types, release-pinned phase model, confidence states, scoring, risk
// indicators, and the progressive-discovery cascade.
export * from './types.js';
