// Analysis core - pure TypeScript with no `vscode` imports. The VS Code extension and the
// Chapter 5 evaluation procedure use structured outputs generated by the same analysis core.
// Home of the domain types, the release-pinned phase model, confidence states, scoring, risk
// indicators, and the progressive-discovery cascade.
export {};
